version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: install sudo
          command: 'apt update && apt install -y sudo && rm -rf /var/lib/at/lists*'
      - run:
          name: install gcc
          command: 'apt update && apt install -y gcc g++'
      - run:
          name: install cmake
          command: 'apt update && sudo apt install -y cmake'
      - run:
          name: library test
          command: ./utils/run_test/run_test.sh
